#https://github-com.translate.goog/musescore/MuseScore/wiki/Compile-on-the-command-line?_x_tr_sl=en&_x_tr_tl=it&_x_tr_hl=it&_x_tr_pto=sc#locating-qt

#sudo apt install build-essential
#sudo apt install make
#sudo apt install cmake
#sudo apt install libglx-dev libgl1-mesa-dev
#sudo apt install libsndfile1-dev
#sudo apt install libasound2-dev
#sudo apt install libxkbcommon-dev
#sudo apt install libz-dev
#sudo apt install ninja-build


option(MUE_COMPILE_QT5_COMPAT "Build with Qt5" OFF)

set(Qt5_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5")
set(Qt53DAnimation_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DAnimation")
set(Qt53DCore_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DCore")
set(Qt53DExtras_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DExtras")
set(Qt53DInput_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DInput")
set(Qt53DLogic_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DLogic")
set(Qt53DQuick_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DQuick")
set(Qt53DQuickAnimation_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DQuickAnimation")
set(Qt53DQuickExtras_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DQuickExtras")
set(Qt53DQuickInput_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DQuickInput")
set(Qt53DQuickRender_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DQuickRender")
set(Qt53DQuickScene2D_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DQuickScene2D")
set(Qt53DRender_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt53DRender")
set(Qt5AccessibilitySupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5AccessibilitySupport")
set(Qt5AttributionsScannerTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5AttributionsScannerTools")
set(Qt5Bluetooth_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Bluetooth")
set(Qt5Bodymovin_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Bodymovin")
set(Qt5Charts_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Charts")
set(Qt5Concurrent_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Concurrent")
set(Qt5Core_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Core")
set(Qt5DataVisualization_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5DataVisualization")
set(Qt5DBus_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5DBus")
set(Qt5Designer_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Designer")
set(Qt5DesignerComponents_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5DesignerComponents")
set(Qt5DeviceDiscoverySupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5DeviceDiscoverySupport")
set(Qt5DocTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5DocTools")
set(Qt5EdidSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5EdidSupport")
set(Qt5EglFSDeviceIntegration_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5EglFSDeviceIntegration")
set(Qt5EglFsKmsSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5EglFsKmsSupport")
set(Qt5EglSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5EglSupport")
set(Qt5EventDispatcherSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5EventDispatcherSupport")
set(Qt5FbSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5FbSupport")
set(Qt5FontDatabaseSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5FontDatabaseSupport")
set(Qt5Gamepad_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Gamepad")
set(Qt5GlxSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5GlxSupport")
set(Qt5Gui_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Gui")
set(Qt5Help_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Help")
set(Qt5InputSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5InputSupport")
set(Qt5InsightTracker_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5InsightTracker")
set(Qt5InsightTrackerQml_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5InsightTrackerQml")
set(Qt5KmsSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5KmsSupport")
set(Qt5LinguistTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5LinguistTools")
set(Qt5LinuxAccessibilitySupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5LinuxAccessibilitySupport")
set(Qt5Location_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Location")
set(Qt5Multimedia_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Multimedia")
set(Qt5MultimediaGstTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5MultimediaGstTools")
set(Qt5MultimediaQuick_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5MultimediaQuick")
set(Qt5MultimediaWidgets_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5MultimediaWidgets")
set(Qt5Network_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Network")
set(Qt5NetworkAuth_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5NetworkAuth")
set(Qt5Nfc_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Nfc")
set(Qt5OpenGL_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5OpenGL")
set(Qt5OpenGLExtensions_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5OpenGLExtensions")
set(Qt5PacketProtocol_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5PacketProtocol")
set(Qt5PlatformCompositorSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5PlatformCompositorSupport")
set(Qt5Positioning_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Positioning")
set(Qt5PositioningQuick_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5PositioningQuick")
set(Qt5PrintSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5PrintSupport")
set(Qt5Purchasing_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Purchasing")
set(Qt5Qml_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Qml")
set(Qt5QmlDebug_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QmlDebug")
set(Qt5QmlDevTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QmlDevTools")
set(Qt5QmlImportScanner_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QmlImportScanner")
set(Qt5QmlModels_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QmlModels")
set(Qt5QmlWorkerScript_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QmlWorkerScript")
set(Qt5Quick_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Quick")
set(Qt5Quick3D_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Quick3D")
set(Qt5Quick3DAssetImport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Quick3DAssetImport")
set(Qt5Quick3DRender_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Quick3DRender")
set(Qt5Quick3DRuntimeRender_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Quick3DRuntimeRender")
set(Qt5Quick3DUtils_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Quick3DUtils")
set(Qt5QuickCompiler_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickCompiler")
set(Qt5QuickControls2_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickControls2")
set(Qt5QuickParticles_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickParticles")
set(Qt5QuickShapes_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickShapes")
set(Qt5QuickTemplates2_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickTemplates2")
set(Qt5QuickTest_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickTest")
set(Qt5QuickWidgets_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5QuickWidgets")
set(Qt5RemoteObjects_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5RemoteObjects")
set(Qt5RepParser_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5RepParser")
set(Qt5Script_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Script")
set(Qt5ScriptTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5ScriptTools")
set(Qt5Scxml_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Scxml")
set(Qt5Sensors_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Sensors")
set(Qt5SerialBus_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5SerialBus")
set(Qt5SerialPort_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5SerialPort")
set(Qt5ServiceSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5ServiceSupport")
set(Qt5Sql_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Sql")
set(Qt5Svg_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Svg")
set(Qt5Test_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Test")
set(Qt5TextToSpeech_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5TextToSpeech")
set(Qt5ThemeSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5ThemeSupport")
set(Qt5UiPlugin_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5UiPlugin")
set(Qt5UiTools_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5UiTools")
set(Qt5VirtualKeyboard_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5VirtualKeyboard")
set(Qt5VulkanSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5VulkanSupport")
set(Qt5WaylandClient_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WaylandClient")
set(Qt5WaylandCompositor_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WaylandCompositor")
set(Qt5WebChannel_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WebChannel")
set(Qt5WebEngine_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WebEngine")
set(Qt5WebEngineCore_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WebEngineCore")
set(Qt5WebEngineWidgets_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WebEngineWidgets")
set(Qt5WebSockets_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WebSockets")
set(Qt5WebView_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5WebView")
set(Qt5Widgets_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Widgets")
set(Qt5X11Extras_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5X11Extras")
set(Qt5XcbQpa_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5XcbQpa")
set(Qt5XkbCommonSupport_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5XkbCommonSupport")
set(Qt5Xml_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5Xml")
set(Qt5XmlPatterns_DIR "/home/amedeo/Qt/5.15.2/gcc_64/lib/cmake/Qt5XmlPatterns")

